# render.yaml
services:
  - type: web
    name: rails-api
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -p 3000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-api-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production

databases:
  - name: rails-api-db
    plan: free
